logging:
  level:
    root: INFO
    org.jooq: TRACE

spring.datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:~/VOTER
  username: username
  password: password

spring.jooq.sql-dialect: H2
spring.jpa.hibernate.ddl-auto: none
